modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Tythee/Minecraft-Reflex/issues"
license = "All rights reserved"

[[mods]]
modId = "reflex"
version = "${version}"
displayName = "Reflex AntiLag"
authors = "Tythee"
description = '''
This mod implements Nvidia Reflex in Minecraft to reduce rendering latency.
'''
logoFile = "assets/reflex/icon.png"

[[dependencies.reflex]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reflex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reflex]]
modId = "cloth_config"
mandatory = true
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
