# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.5
maven_group = io.tythee
archives_name = reflex
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
fabric_loader_version = 0.19.2
fabric_api_version = 0.154.0+26.2
neoforge_version = 26.2.0.8-beta
modmenu_version=20.0.0-beta.4
cloth_config_version=26.2.155