# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.4
maven_group = io.tythee
archives_name = reflex
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.2
fabric_api_version = 0.148.0+26.1.2
neoforge_version = 26.1.2.76
modmenu_version=18.0.0-beta.1
cloth_config_version=26.1.154