architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // Fabric API.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    
    // Cloth Config API.
    api("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}
}
