name: Build and Upload Artifacts
on:
  push:
    branches: ['*']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Build with Gradle
        run: ./gradlew buildAll --no-daemon --console=plain
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reflex-artifacts
          path: build/libs/**/*.jar